### ISSUE TITLE
API Reference Docs - Docs Revamp

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#1031]
* The developer API product and only the developer API product needs to be documented to fulfill this rock. This requires:
    * The product owners (PM) to definitively determine what portions of the codebase are part of the developer API product & what is the rest of the platform.
    * Reference docs must be auto-generated for the entire developer API product.
    * Code examples for all portions of the developer API product must be linked from the relevant sections of the docs site. Code examples can be a mix of inline examples on the docs site, links to relevant lines of contracts or sample dapps. 

```[tasklist]
### Tasks
- [x] Publish initial typedoc for endo: https://endojs.github.io/endo/
- [x] https://github.com/Agoric/documentation/issues/1064
- [ ] https://github.com/endojs/endo/pull/2181
- [ ] https://github.com/Agoric/documentation/issues/1032
- [ ] https://github.com/Agoric/documentation/issues/1047
- [ ] https://github.com/Agoric/agoric-sdk/issues/8852
- [ ] https://github.com/Agoric/agoric-sdk/issues/4291
- [ ] https://github.com/Agoric/documentation/issues/1061
- [ ] https://github.com/Agoric/documentation/issues/1060
- [ ] https://github.com/Agoric/documentation/issues/1062
- [ ] https://github.com/Agoric/documentation/issues/1063
- [ ] https://github.com/Agoric/documentation/issues/431
- [ ] https://github.com/Agoric/documentation/issues/883
```

**Comment by dckc** [comment]
tasks that come to mind:

 - [x] Publish initial typedoc for endo: https://endojs.github.io/endo/
 - Publish initial typedoc for agoric-sdk
   - [ ] choose URL
   - [ ] continuous deployment
 - [ ] Publish initial typedoc for ui-kit
   - [ ] choose URL
   - [ ] continuous deployment
 - [ ] Gap analysis: what does dapp-offer-up use that we don’t have acceptable reference doc for?
For example: is [reference doc for E](https://endojs.github.io/endo/functions/_endo_eventual_send.E.html) acceptable?
 - [ ] Gap analysis: what does dapp-agoric-basics use that we don’t have acceptable reference doc for?

**Comment by dckc** [comment]
stretch goal:

 - https://github.com/Agoric/documentation/issues/927
