### ISSUE TITLE
Revise the Getting Started section

### ISSUE THREAD

**Issue by Tyrosine22** [Agoric/documentation#760]
```[tasklist]
### Tasks
- [ ] Use a Simple Exchange dapp as an example dapp rather than the fungible faucet dapp.
- [ ] #761
- [ ] Verify & clean up all the steps in the first 2 topics.
- [ ] From bug #391 (which I've closed as a duplicate): There is a fix necessary to agoric-cli to report when there isn't an executable available, and to make -v work. AND the --reset option is relevant both for starting the local chain and for starting the local ag-solo. (their persistent state is independent)
- [ ] Create a "bridge" between the first 2 topics and the discussion of zoe.
```

**Comment by Tyrosine22** [comment]
This revision involves the following subtasks:

1. Use a Simple Exchange dapp as an example dapp rather than the fungible faucet dapp. (Note: I'll also have to either implement or fix said app.)
2. Verify & clean up all the steps in the first 2 topics.
3. From bug #391 (which I've closed as a duplicate): There is a fix necessary to agoric-cli to report when there isn't an executable available, and to make -v work. AND the --reset option is relevant both for starting the local chain and for starting the local ag-solo. (their persistent state is independent)
4. Create a "bridge" between the first 2 topics and the discussion of zoe.

**Comment by dckc** [comment]
fixed as part of 

 - #726 

re bridge, see:

 - #891
