### ISSUE TITLE
Page 2 - How to mint tickets to an event

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/documentation#939]
Goal: A new contract to create NFT Drop. 

Use-case: TicketStub is a form that allows users to buy NFTs representing seats. 

This use-case will show 3 rows of seats.

Row 1: $100 each seat (3 NFT tickets)
Row 2: $ 50 each seat (3 NFT tickets)
Row 3: $ 25 each seat (3 NFT tickets)

Result: 
NFT Ticket should land in the User's Smart Wallet.

Relevant docs:
 - [dapp-agoric-basics PRD](https://docs.google.com/document/d/1wUgp4o9pmiva2qRDq-smYolBQ-mzo0uJhCNuQCt6EUg/edit#heading=h.456n8jqmuwqu) google doc
 - [Docs Revamp](https://miro.com/app/board/uXjVNy24pko=/)  miro board

```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/dapp-agoric-basics/pull/8
- [ ] https://github.com/Agoric/documentation/issues/977
- [ ] Document key take away lessons from this contract
- [ ] Video lesson showing highlighting mint code and how it works
```

**Comment by dckc** [comment]
I don't see a separate ticket for the UI part, so I suppose the updated UI target belongs here:

![image](https://github.com/Agoric/documentation/assets/150986/62b6d95a-bd41-4f64-9eea-e779bcc6eb3e)

**Comment by LuqiPan** [comment]
@sufyaankhan where are we on creating separate tickets for UI tasks?

**Comment by sufyaankhan** [comment]
Here you go @LuqiPan 
https://github.com/Agoric/documentation/issues/977

**Comment by kbennett2000** [comment]
Remaining steps:

1. Document key take away lessons from this contract
2. Video lesson showing highlighting mint code and how it works

**Comment by dckc** [comment]
#1017 is not merged

**Comment by kbennett2000** [comment]
Can this issue be closed now?

**Comment by kbennett2000** [comment]
I'm no longer at Agoric and can't remove myself as assignee (no triage access on this repo). Could a maintainer unassign me? Filtering issues by `assignee:kbennett2000` will catch the rest in one go. Thanks!
@dckc  @dtribble
